### ISSUE TITLE
Deprecation warning for node-12

### ISSUE THREAD

**Issue by andreasabel** [svenstaro/upx-action#27]
@svenstaro: [I am getting](https://github.com/agda/agda/actions/runs/3276470409): 
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: svenstaro/upx-action

Maybe this can be fixed by releasing this automatic PR?
- #25

**Comment by svenstaro** [comment]
Yeah I'm aware. I want to rewrite the extension soon anyway as it's super outdated.

**Comment by svenstaro** [comment]
Please check the current master and test it a little. Once you report back everything's working for you, I'll cut a release proper.

**Comment by andreasabel** [comment]
@svenstaro : I am happy to do this.  
Is master ready yet?  CI E2E still fails there on macOS.

**Comment by svenstaro** [comment]
Yeah so there's a problem that I can't figure out. I need to somehow acquire the prebuilt binaries for the right version of node on osx but they do not exist it seems.

**Comment by andreasabel** [comment]
I started the test here: https://github.com/agda/agda/actions/runs/3872715248

**Comment by andreasabel** [comment]
> Yeah so there's a problem that I can't figure out. I need to somehow acquire the prebuilt binaries for the right version of node on osx but they do not exist it seems.

Ok, so likely the test I started will fail.

**Comment by andreasabel** [comment]
It does fail, even under ubuntu-20.04: https://github.com/agda/agda/actions/runs/3872715248/jobs/6601896588#step:13:11
```
node:internal/modules/cjs/loader:[11](https://github.com/agda/agda/actions/runs/3872715248/jobs/6601896588#step:13:12)83
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/runner/work/_actions/svenstaro/upx-action/master/node_modules/lzma-native/binding-v4.0.6-node-v93-linux-x64/lzma_native.node)
```

The other failure is likely known to you:
- Windows: https://github.com/agda/agda/actions/runs/3872715248/jobs/6601896298#step:13:11
```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'D:\a\_actions\svenstaro\upx-action\master\node_modules\lzma-native\binding-v4.0.6-node-v93-win32-x64\lzma_native.node'
```

It succeeds on `macOS-latest`.

**Comment by svenstaro** [comment]
Please test now, should be fixed.

**Comment by andreasabel** [comment]
Thanks.  I started a new test at: https://github.com/agda/agda/actions/runs/3900938484

Works!
