### ISSUE TITLE
How to set the UPX version

### ISSUE THREAD

**Issue by aharpervc** [svenstaro/upx-action#38]
Hi, I've started using this action, and it generally works fine. However, I see this warning in the CI log:

```
Downloading UPX...
/usr/local/bin/brew install upx
Warning: upx has been deprecated because it is crashing for macOS Ventura or above!
==> Downloading https://ghcr.io/v2/homebrew/core/upx/manifests/4.1.0
```

Is there a way to use a newer version of UPX, or specify which version to use?

**Comment by svenstaro** [comment]
This is really odd. Apparently it's being removed from homebrew? I think it would be a good idea to open a dialog with upx upstream and homebrew and maybe actually figure out why it's crashing and if it can't be fixed. Also, homebrew was shipping version 4.1.0 while there's 4.2.1. So I suggest you build upx 4.2.1 with the homebrew formula and see if it still crashes. If it doesn't, submit a PR to homebrew to have it reinstated.

**Comment by aharpervc** [comment]
> So I suggest you build upx 4.2.1 with the homebrew formula and see if it still crashes.

Is this something that can be done within a CI step?

**Comment by svenstaro** [comment]
Potentially yes but it's not really our job to fix upstream bugs in this repo. I think it's much better to just have upstream take a look at that themselves.
