### ISSUE TITLE
Response code 404 (Not Found)

### ISSUE THREAD

**Issue by crazy-max** [svenstaro/upx-action#4]
Looks like UPX binaries [are not available](https://github.com/crazy-max/WindowsSpyBlocker/commit/9afcb25fff5d5f235be132ef3c139aba7280934b/checks?check_suite_id=390584450#step:7:1).

```
Run svenstaro/upx-action@v1-release
⬇️ Downloading UPX...
##[error]Response code 404 (Not Found)
(node:3188) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (d:\a\_actions\svenstaro\upx-action\v1-release\node_modules\got\index.js:482:24)
    at EventEmitter.emit (events.js:210:5)
    at getResponse (d:\a\_actions\svenstaro\upx-action\v1-release\node_modules\got\index.js:320:5)
    at Immediate.<anonymous> (d:\a\_actions\svenstaro\upx-action\v1-release\node_modules\got\index.js:147:6)
    at processImmediate (internal/timers.js:439:21)
(node:3188) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3188) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
##[error]Node run failed with exit code 1
```

**Comment by crazy-max** [comment]
@svenstaro Not found again with links provided by #5

**Comment by svenstaro** [comment]
Crap. They really need to make a new official release.

**Comment by svenstaro** [comment]
I just checked. They've started removing older automatic builds which didn't happen earlier.  We might have to rehost some files.

**Comment by svenstaro** [comment]
Something is happening over here: https://github.com/upx/upx/issues/300

Hopefully, we'll see a release soon!

**Comment by crazy-max** [comment]
Ok thanks @svenstaro,
In the meantime I have created another action to use official releases of UPX if you want to take a look: https://github.com/crazy-max/ghaction-upx

**Comment by svenstaro** [comment]
Thanks for the hint. Sadly for my use case, it's not useful as I need some changes which only exist on the nightlies. :(

**Comment by svenstaro** [comment]
There's a new release! https://github.com/upx/upx/releases

It's not as easy as plugging in the new URLs as we'll also have to extract these compressed files. Would you like to take a stab at that?

**Comment by svenstaro** [comment]
Fixed now for real. :)
